services:
  tailscale-sc:
    image: tailscale/tailscale:latest
    hostname: sidecar
    environment:
    # - TS_AUTHKEY=/run/secrets/ts_authkey
     - TS_CUBE_SECRET=/run/secrets/ts_authkey
     - TS_STATE_DIR=/var/lib/tailscale
     - TS_USERSPACE=false
     - TS_SERVE_CONFIG=/config/serve-config.json
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./state:/var/lib/tailscale
      - ./config:/config
    secrets:
      - ts_authkey
    restart: unless-stopped

secrets:
  ts_authkey:
    file: ./ts_authkey.txt