services:
  tailscale-sc:
    image: tailscale/tailscale:latest
    container_name: sidecar
    env_file:
     - ./ts_authkey.env
    environment:
    # - TS_AUTHKEY= ${TS_AUTHKEY} in der env_file zu setzen
     - TS_STATE_DIR=/var/lib/tailscale
     - TS_USERSPACE=false
     - TS_SERVE_CONFIG=/config/serve-config.json
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./state:/var/lib/tailscale
      - ./config:/config
    restart: unless-stopped