services:
  ts-sidecar:
    image: tailscale/tailscale:latest
    container_name: sidecar
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    #  - TS_SERVE_CONFIG=/config/serve-config.json
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./ts/state:/var/lib/tailscale
      - ./ts/config:/config
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes: 
      - ./jelly/config:/config
      - ./jelly/cache:/cache
      #- type: bind
      #  source: /path/to/media
      #  target: /media
      #- type: bind
      #  source: /path/to/media2
      #  target: /media2
      #  read_only: true
    network_mode: "service:ts-sidecar"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${TAILNET_NAME}.ts.net
    depends_on: 
      - ts-sidecar
    restart: unless-stopped